/* Criacao do banco DATABASE-MUSEUM */
CREATE DATABASE IF NOT EXISTS `DATABASE-MUSEUM`;

/* Conecta ao banco DATABASE-MUSEUM */
USE `DATABASE-MUSEUM`;

/* Criacao da tabela TB_ARTE */
CREATE TABLE IF NOT EXISTS `TB_ARTE` (ID BIGINT NOT NULL, NOME_OBRA VARCHAR(255), NOME_ARTISTA VARCHAR(255), DATA_CRIACAO DATE, DESCRICAO VARCHAR(255));

/* Criacao da tabela TB_DOADOR */
CREATE TABLE IF NOT EXISTS `TB_DOACAO` (ID BIGINT NOT NULL, NOME_INSTITUICAO VARCHAR(255), CNPJ VARCHAR(255), VALOR_DOADO DOUBLE, DATA_DOACAO DATE, DESCRICAO VARCHAR(255));

/* Criacao da tabela TB_FUNCIONARIO */
CREATE TABLE IF NOT EXISTS `TB_FUNCIONARIO` (ID BIGINT NOT NULL, NOME VARCHAR(255), CPF VARCHAR(255), TELEFONE VARCHAR(255), CARGO VARCHAR(255), TURNO VARCHAR(255), EMAIL VARCHAR(255), SENHA VARCHAR(255));

/* Criacao da tabela TB_RESERVA */
CREATE TABLE IF NOT EXISTS `TB_RESERVA` (ID BIGINT NOT NULL, NOME VARCHAR(255), CPF VARCHAR(255), TELEFONE VARCHAR(255), QUANTIDADE_PESSOAS INTEGER, DATA_RESERVA DATE, HORA_INICIO VARCHAR(255));

/* Adicionar PK nas tabelas */
ALTER TABLE `TB_ARTE` ADD CONSTRAINT PK_TB_ARTE PRIMARY KEY (ID);
ALTER TABLE `TB_ARTE` MODIFY ID BIGINT AUTO_INCREMENT;

ALTER TABLE `TB_DOACAO` ADD CONSTRAINT PK_TB_DOACAO PRIMARY KEY (ID);
ALTER TABLE `TB_DOACAO` MODIFY ID BIGINT AUTO_INCREMENT;

ALTER TABLE `TB_FUNCIONARIO` ADD CONSTRAINT PK_TB_FUNCIONARIO PRIMARY KEY (ID);
ALTER TABLE `TB_FUNCIONARIO` MODIFY ID BIGINT AUTO_INCREMENT;

ALTER TABLE `TB_RESERVA` ADD CONSTRAINT PK_TB_RESERVA PRIMARY KEY (ID);
ALTER TABLE `TB_RESERVA` MODIFY ID BIGINT AUTO_INCREMENT;

DELIMITER $$
CREATE PROCEDURE GRAFICO_QUANTIDADE_VISITAS_POR_MES()
BEGIN
    SELECT
        SUM(QUANTIDADE_PESSOAS) QUANTIDADE_PESSOAS_POR_MES,
        EXTRACT(YEAR FROM DATA_RESERVA) ANO,
        EXTRACT(MONTH FROM DATA_RESERVA) MES
    FROM
        TB_RESERVA
    GROUP BY
        ANO, MES
    ORDER BY
        ANO, MES;
END$$
DELIMITER ;

# CALL GRAFICO_QUANTIDADE_VISITAS_POR_MES();
# DROP PROCEDURE GRAFICO_QUANTIDADE_VISITAS_POR_MES;

DELIMITER $$
CREATE PROCEDURE RELATORIO_VALOR_TOTAL_DOADO_POR_MES()
BEGIN
    SET lc_time_names = 'pt_BR';
    SELECT
        CONVERT(SUM(VALOR_DOADO), DECIMAL(65,2)) VALOR_TOTAL_DOADO_POR_MES,
        EXTRACT(YEAR FROM DATA_DOACAO) ANO,
        MONTHNAME(STR_TO_DATE(EXTRACT(MONTH FROM DATA_DOACAO), '%m')) MES
    FROM
        TB_DOACAO
    GROUP BY
        ANO, (EXTRACT(MONTH FROM DATA_DOACAO))
    ORDER BY
        ANO, (EXTRACT(MONTH FROM DATA_DOACAO));
END$$
DELIMITER ;

# CALL RELATORIO_VALOR_TOTAL_DOADO_POR_MES();
# DROP PROCEDURE RELATORIO_VALOR_TOTAL_DOADO_POR_MES;