algoritmo "Exercicio19"

var

   num1, num2 : real

inicio

   escreval("Digite o primeiro numero: ")
   Leia (num1)
   escreval("Digite o segundo numero: ")
   Leia (num2)

   se (num1 >= num2) entao
      se (num1 > num2) ENTAO
         escreval("O maior valor e  ", num1)
      senao
         escreval("Os valores sao iguais")
      fimse
   senao
      escreval("O maior valor e  ", num2)
   fimse

fimalgoritmo