/* 
CRIAR TRIGGER QUE:
IMPEÇA A INCLUSAO DE PROFESSOR SEM TITULO DE DOUTORADO
*/

USE AULA_12_09_05_2022;

DROP TRIGGER IF EXISTS TGR_INSERT_PROFESSOR_DOUTOR;

DELIMITER $$
CREATE TRIGGER TGR_INSERT_PROFESSOR_DOUTOR 
BEFORE INSERT
ON TB_PROFESSOR
FOR EACH ROW
BEGIN
	IF ((SELECT 
		NOME_TIT
	FROM 
		TB_TITULACAO 
	WHERE 
		COD_TIT = NEW.COD_TIT) != 'Doutor')
	THEN
        SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'ERROR! Nao pode inserir, o professor nao e doutor.';
	END IF;
END $$
DELIMITER ;

INSERT INTO TB_PROFESSOR(COD_PROF, COD_DEPTO, COD_TIT, NOME_PROF) VALUES (5, 'INF01', 1, 'TESTE DOUTOR');
INSERT INTO TB_PROFESSOR(COD_PROF, COD_DEPTO, COD_TIT, NOME_PROF) VALUES (6, 'INF01', 2, 'TESTE NAO DOUTOR');